CREATE TABLE `dm_ordi_predict.dws_air_flow_six_dims_waybill_dtl_backup20230620`( `consigned_tm` string COMMENT '寄件时间', `waybill_no` string COMMENT '运单号', `quantity` string COMMENT '件数', `meterage_weight_qty` string COMMENT '计费重量', `product_code` string COMMENT '产品代码', `limit_type_code` string COMMENT '时效类型', `limit_tag` string COMMENT '', `if_shoes_cust` string COMMENT '是否鞋服大客户', `if_econ_fresh` string COMMENT '是否特色经济', `pro_name` string COMMENT '特色经济-项目', `level_1_type` string COMMENT '特色经济一级类目', `level_2_type` string COMMENT '特色经济二级类目', `companyabbr` string COMMENT '', `custtypename` string COMMENT '', `freight_monthly_acct_code` string COMMENT '月结卡号', `city_flow` string COMMENT '城市流向对', `src_city_name` string COMMENT '起始城市名称', `dest_city_name` string COMMENT '目的城市名称', `type` string COMMENT '维度') PARTITIONED BY ( `inc_day` string COMMENT '寄件日期yyyymmdd') ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat' ;


CREATE TABLE `dm_ordi_predict.dws_air_flow_six_dims_day_backup20230620`( `days` string COMMENT '收件日期', `city_flow` string COMMENT '流向对', `src_city_name` string COMMENT '起始城市名称', `dest_city_name` string COMMENT '目的城市名称', `type` string COMMENT '维度', `air_waybill_num` int COMMENT '航空运单量', `air_quentity_num` int COMMENT '航空件量改', `air_sum_weight` double COMMENT '航空总重量', `air_avg_weight` double COMMENT '航空平均重量', `air_mid_weight` double COMMENT '航空中位数重量') PARTITIONED BY ( `inc_day` string COMMENT '预测日期yyyymmdd') ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat' ;


CREATE TABLE `dm_ordi_predict.dws_air_flow_six_dims_day_newhb_backup20230620`( `days` string COMMENT '收件日期', `city_flow` string COMMENT '流向对', `src_city_name` string COMMENT '起始城市名称', `dest_city_name` string COMMENT '目的城市名称', `type` string COMMENT '维度', `air_waybill_num` int COMMENT '航空运单量', `air_quentity_num` int COMMENT '航空件量', `air_sum_weight` double COMMENT '航空总重量', `air_avg_weight` double COMMENT '航空平均重量', `air_mid_weight` double COMMENT '航空中位数重量', `src_province` string COMMENT '起始省份', `dest_province` string COMMENT '目的省份', `avg_weight` double COMMENT '件均重（来自规调）', `sum_avg_weight` double COMMENT '总重量（件均重*件量）') PARTITIONED BY ( `inc_day` string COMMENT '预测日期yyyymmdd') ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat';


CREATE TABLE `dm_ordi_predict.dws_static_cityflow_special_econ_day_backup20230620`( `days` string COMMENT '收件日期', `city_flow` string COMMENT '流向对', `src_city_name` string COMMENT '起始城市名称', `dest_city_name` string COMMENT '目的城市名称', `is_air` string COMMENT '是否航空流向', `pro_name` string COMMENT '项目名称', `level_1_type` string COMMENT '一级类目', `level_2_type` string COMMENT '二级类目', `all_waybill_num` int COMMENT '运单量', `all_quantity_num` int COMMENT '件量', `all_weight` double COMMENT '总重量', `avg_weight` string COMMENT '票平均重量', `mid_weight` double COMMENT '票中位数重量', `air_waybill_num` int COMMENT '航空运单量', `air_quantity_num` int COMMENT '航空件量', `air_sum_weight` double COMMENT '航空总重量', `air_avg_weight` string COMMENT '航空平均重量', `air_mid_weight` double COMMENT '航空中位数重量', `all_volume_num` double COMMENT '总体积', `avg_volume` double COMMENT '平均体积', `mid_volume` double COMMENT '体积中位数', `air_volume_num` double COMMENT '航空总体积', `air_avg_volume` double COMMENT '航空平均体积', `air_mid_volume` double COMMENT '航空体积中位数') PARTITIONED BY ( `inc_day` string COMMENT '预测日期yyyymmdd') ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat';


CREATE TABLE `dm_ordi_predict.dws_air_flow_five_dims_day_sub_backup20230620`( `days` string COMMENT '收件日期', `city_flow` string COMMENT '流向对', `src_city_name` string COMMENT '起始城市名称', `dest_city_name` string COMMENT '目的城市名称', `type` string COMMENT '维度', `air_waybill_num` int COMMENT '航空运单量', `air_quentity_num` int COMMENT '航空件量', `air_sum_weight` double COMMENT '航空总重量', `air_avg_weight` double COMMENT '航空平均重量', `air_mid_weight` double COMMENT '航空中位数重量', `src_province` string COMMENT '起始省份', `dest_province` string COMMENT '目的省份', `avg_weight` double COMMENT '件均重（来自规调）', `sum_avg_weight` double COMMENT '总重量（件均重*件量）') PARTITIONED BY ( `inc_day` string COMMENT '预测日期yyyymmdd') ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat';