-- 791707
tmp_ordi_predict.super_flow_vehicle_tasks_split_info_full_hudi_pro_rt_tmp_gaofeng_v1
tmp_ordi_predict.spuer_flow_container_result_info_tmp_gaofeng_v1 
tmp_ordi_predict.dwd_pass_trans_waybill_dtl_di_tmp_gaofeng_v1
tmp_ordi_predict.dwd_st_batch_info_di_tmp_gaofeng_v1
tmp_ordi_predict.dws_trans_next_zone_vote_weight_avg_di_tmp_gaofeng_v1 


-- 796562
tmp_ordi_predict.super_flow_vehicle_tasks_split_info_full_hudi_pro_rt_tmp_gaofeng_v2
tmp_ordi_predict.spuer_flow_container_result_info_tmp_gaofeng_v2
tmp_ordi_predict.super_flow_pis_batch_flow_stat_result_hour_tmp_gaofeng_v2
tmp_ordi_predict.dwd_st_batch_info_di_tmp_gaofeng_v2
tmp_ordi_predict.dws_trans_next_zone_vote_weight_avg_di_tmp_gaofeng_v2


-- 809630
tmp_ordi_predict.dwd_waybill_weight_kg_info_df_tmp_gaofeng_v1
tmp_ordi_predict.dim_customer_info_df_tmp_gaofeng_v1


-- 815979
tmp_ordi_predict.dws_fc_sp_predict_collecting_di_tmp_gaofeng_v1


--852691
tmp_ordi_predict.tm_air_transport_cargo_pro_tmp_gaofeng_v1
tmp_ordi_predict.aira_tm_air_transport_batch_pro_tmp_gaofeng_v1


-- 853359
tmp_ordi_predict.super_flow_vehicle_tasks_split_info_full_hudi_pro_rt_tmp_gaofeng_v1
tmp_ordi_predict.aira_tm_air_transport_batch_pro_tmp_gaofeng_v1
tmp_ordi_predict.scha_tt_transport_schedule_pro_tmp_gaofeng_v1

--807606
tmp_ordi_predict.dwd_waybill_info_dtl_di_tmp_gaofeng_v3
tmp_ordi_predict.dwd_waybill_consign_category_info_di_tmp_gaofeng_v1

-- 448434
tmp_ordi_predict.dwd_waybill_info_dtl_di_tmp_gaofeng_v5
tmp_ordi_predict.dwd_waybill_consign_category_info_di_tmp_gaofeng_v5
tmp_ordi_predict.dm_zz_air_waybill_avg_weight_tmp_gaofeng_v5

dm_ordi_predict.dws_spec_consign_waybill_day  -> tmp_ordi_predict.dws_spec_consign_waybill_day_tmp_gaofeng_v5
dm_ordi_predict.dws_spec_eco_pro_waybill_day  -> tmp_ordi_predict.dws_spec_eco_pro_waybill_day_tmp_gaofeng_v5
dm_ordi_predict.dws_air_flow_six_dims_waybill_dtl  -> tmp_ordi_predict.dws_air_flow_six_dims_waybill_dtl_tmp_gaofeng_v5
dm_ordi_predict.dws_air_flow_six_dims_day  -> tmp_ordi_predict.dws_air_flow_six_dims_day_tmp_gaofeng_v5
dm_ordi_predict.dws_air_flow_six_dims_day_newhb  -> tmp_ordi_predict.dws_air_flow_six_dims_day_newhb_tmp_gaofeng_v5
dm_ordi_predict.dws_static_cityflow_special_econ_day  -> tmp_ordi_predict.dws_static_cityflow_special_econ_day_tmp_gaofeng_v5
dm_ordi_predict.dws_air_flow_five_dims_day_sub  -> tmp_ordi_predict.dws_air_flow_five_dims_day_sub_tmp_gaofeng_v5


-- 663166 【压测-871416】
tmp_ordi_predict.dm_full_order_dtl_df_tmp_gaofeng_v1
tmp_ordi_predict.tt_waybill_no_to_order_no_tmp_gaofeng_v1
tmp_ordi_predict.dwd_pis_route_info_v2_df_tmp_gaofeng_v1

-- 663166  【内存设置24g 871987】


drop table if exists tmp_ordi_predict.dwd_st_batch_info_di_tmp_gaofeng_v1;
create table if not exists tmp_ordi_predict.dwd_st_batch_info_di_tmp_gaofeng_v1 
stored as parquet as

_tmp_gaofeng_v1
_tmp_gaofeng_v2

_tmp_gaofeng_v5